### ISSUE TITLE
corrupted dataset handling

### ISSUE THREAD

**Issue by yachang** [m-lab/annotation-service#104]
Currently we allow the corrupted data to some extent in the data loading stage.

But if a database always fails to load, the cache should mark it as unloadable, and use a different dataset for that date range.

Or a more simple solution, we keep a backup version, but delete the corrupted dataset from the GCS for prod usage.

**Comment by pboothe** [comment]
Ya will connect this to PRs.

**Comment by yachang** [comment]
Fixed by PR #103 which allowed up to 100 row errors during loading Geolite2 dataset row by row.
