### ISSUE TITLE
The load-archive merge caused Bad Gateway problems

### ISSUE THREAD

**Issue by gfr10598** [m-lab/annotation-service#138]
This became apparent when looking at etl pipeline in staging.  Discovered after basing a new sandbox branch on master with the merged load-archive code.

I have NOT rolled back or fixed the code.  I HAVE reverted the versions running in both sandbox and staging, but the problem will recur if we redeploy this code.

**Comment by gfr10598** [comment]
Another hint at possible cause - profile showed a large amount of time spent in futex?  Also, prometheus was getting very occasional snapshots, so the servers were there, but usually unresponsive.

**Comment by pboothe** [comment]
Obsolete.
