### ISSUE TITLE
At 1900 UTC, instances started shutting down

### ISSUE THREAD

**Issue by gfr10598** [m-lab/annotation-service#161]
For unknown reason, instances of version that was working fine started shutting down and restarting.  Number of instances was generally below the configured minimum.  Requests were frequently getting Bad Gateway responses.

This did not relate to any new deployment.  Seems to be persisting.

Version was annotator-20181220t162720

runtime: custom
api_version: '1.0'
env: flexible
threadsafe: true
env_variables:
  COMMIT_HASH: '${TRAVIS_COMMIT}'
  RELEASE_TAG: '${TRAVIS_TAG}'
automatic_scaling:
  min_num_instances: 5
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.6
network:
  instance_tag: annotator
  forwarded_ports:
    - 9090/tcp
  name: default
resources:
  cpu: 10
  memory_gb: 60
  disk_size_gb: 100

**Comment by gfr10598** [comment]
It now looks like there are residual instances of 230959 that are flapping, and 5 instances of 231047 that are stable.  Something is wrong, because app-engine is only sending traffic to the older version, which is the one that is flapping.

**Comment by gfr10598** [comment]
Looking at logs around 15:32:46.  instance rrzq is shutting down.  See "uploading crash log"
"rrzq in version 20181220t230959 never went healthy."

https://pantheon.corp.google.com/logs/viewer?project=mlab-sandbox&organizationId=433637338589&resource=gae_app%2Fmodule_id%2Fannotator%2Fversion_id%2F20181220t230959&minLogLevel=0&expandAll=false&timestamp=2018-12-21T15:03:23.027000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-12-21T15:30:00.665Z&dateRangeEnd=2018-12-21T15:33:00.665Z&interval=CUSTOM&scrollTimestamp=2018-12-21T15:32:51.191908113Z&logName=projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fvm.events&logName=projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fvm.shutdown&logName=projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fvm.syslog&filters=text:rrzq

**Comment by gfr10598** [comment]
There are a lot of these:
[error] 41#41: *726 connect() failed (111: Connection refused) while connecting to upstream, client: 74.125.31.153, server: , request: "POST /batch_annotate HTTP/1.1", upstream: "http://172.17.0.1:8080/batch_annotate", host: "annotator-dot-mlab-sandbox.appspot.com"

This seems odd because I wouldn't expect appengine to send client traffic when the instance isn't healthy, and all the health checks are also failing.

**Comment by gfr10598** [comment]
There is a clear point in time where the health checks start failing:
(in reverse order - most recent at the top)

A  GET 502 150 B 0 ms GoogleHC/1.0 /_ah/health GET 502 150 B 0 ms GoogleHC/1.0 
A  GET 502 150 B 0 ms GoogleHC/1.0 /_ah/health GET 502 150 B 0 ms GoogleHC/1.0 
A  GET 502 150 B 0 ms GoogleHC/1.0 /_ah/health GET 502 150 B 0 ms GoogleHC/1.0 
A  [error] 41#41: *796 connect() failed (111: Connection refused) while connecting to upstream, client: 130.211.1.212, server: , request: "GET /_ah/health HTTP/1.1", upstream: "http://172.17.0.1:8080/_ah/health", host: "10.142.0.11" 
A  [error] 41#41: *791 connect() failed (111: Connection refused) while connecting to upstream, client: 130.211.1.211, server: , request: "GET /_ah/health HTTP/1.1", upstream: "http://172.17.0.1:8080/_ah/health", host: "10.142.0.11" 
A  [error] 41#41: *785 connect() failed (111: Connection refused) while connecting to upstream, client: 130.211.1.210, server: , request: "GET /_ah/health HTTP/1.1", upstream: "http://172.17.0.1:8080/_ah/health", host: "10.142.0.11" 
A  GET 502 150 B 1 ms GoogleHC/1.0 /_ah/health GET 502 150 B 1 ms GoogleHC/1.0 
A  Dec 21 15:32:44 aef-annotator-20181220t230959-rrzq kernel: [  141.384837] docker0: port 5(veth8fd816a) entered disabled state 
A  Dec 21 15:32:44 aef-annotator-20181220t230959-rrzq kernel: [  141.378749] device veth8fd816a left promiscuous mode 
A  Dec 21 15:32:44 aef-annotator-20181220t230959-rrzq kernel: [  141.369481] docker0: port 5(veth8fd816a) entered disabled state 
A  Dec 21 15:32:44 aef-annotator-20181220t230959-rrzq kernel: [  141.303564] vethb96e339: renamed from eth0 
A  Dec 21 15:32:44 aef-annotator-20181220t230959-rrzq kernel: [  141.297204] docker0: port 5(veth8fd816a) entered disabled state 
A  GET 200 2 B 1 ms GoogleHC/1.0 /_ah/health GET 200 2 B 1 ms GoogleHC/1.0 
A  GET 200 2 B 0 ms GoogleHC/1.0 /_ah/health GET 200 2 B 0 ms GoogleHC/1.0

**Comment by gfr10598** [comment]
At 17:31 migrated traffic over to newer 231047 version.  Immediately started seeing health checks alternating between success and failure in blocks of about 10 - 15 seconds each.

Sometimes see:
Dec 21 17:32:09 aef-annotator-20181220t231047-pf2j kernel: [65883.842457] IPv6: eth0: IPv6 duplicate address fe80::42:acff:fe11:6 detected!

Also seems to be eth activity, like:
A  GET 502 150 B 0 ms GoogleHC/1.0 /_ah/health GET 502 150 B 0 ms GoogleHC/1.0 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.420348] ll header: 00000000: ff ff ff ff ff ff 02 42 ac 11 00 06 08 06        .......B...... 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.413045] IPv4: martian source 172.17.0.4 from 172.17.0.6, on dev eth0 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.384719] eth0: renamed from vethed4f857 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j systemd-udevd[4246]: Could not generate persistent MAC address for vethed4f857: No such file or directory 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j systemd-udevd[4247]: Could not generate persistent MAC address for veth21881c5: No such file or directory 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.256767] docker0: port 5(veth21881c5) entered forwarding state 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.249367] docker0: port 5(veth21881c5) entered blocking state 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.242460] device veth21881c5 entered promiscuous mode 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.236194] docker0: port 5(veth21881c5) entered disabled state 
A  Dec 21 17:38:06 aef-annotator-20181220t231047-pf2j kernel: [66241.229828] docker0: port 5(veth21881c5) entered blocking state 

Checked quotas and don't see any problems.

**Comment by gfr10598** [comment]
Search for "unhealthy" shows clean break in the health summaries when traffic was migrated.  Perfectly happy until requests started, then roughly 1/2 to 2/3 unhealthy within each 1 minute interval.

**Comment by gfr10598** [comment]
Confusing:  The process_start_time_seconds seems to flap with the health, even though it doesn't look like the instance is actually shutting down and restarting.  It is just going unhealthy, then healthy again.

**Comment by gfr10598** [comment]
Argh.  Peter suggests it may have to do with using a bad dataset (or annotator).  Looking through monitoring history, the last time we had clean monitoring in sandbox was 20181215t190015.  Those versions are no longer available in appengine, so slightly hard to recreate.  This makes it more likely to be related to legacy datasets somehow causing hangs in the server.

**Comment by gfr10598** [comment]
Disabling legacy resolved the problem.  Looking through history, it was behaving this way since 12/16.  Probably triggered yesterday when gardener wrapped back to earlier dates?

**Comment by gfr10598** [comment]
Re-opening so we can resolve the underlying problem.

**Comment by gfr10598** [comment]
I think the relevant logs are here:
https://pantheon.corp.google.com/logs/viewer?project=mlab-staging&organizationId=433637338589&minLogLevel=0&expandAll=false&timestamp=2018-12-14T01:19:30.000000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-12-13T16:51:13.000Z&dateRangeEnd=2018-12-14T03:51:13.000Z&interval=CUSTOM&resource=gae_app%2Fmodule_id%2Fannotator%2Fversion_id%2F20181213t203529&logName=projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&scrollTimestamp=2018-12-14T01:16:28.000000000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22annotator%22%0Aresource.labels.version_id%3D%2220181213t203529%22%0AlogName%3D(%22projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fstderr%22%20OR%20%22projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fnginx.request%22)%0AhttpRequest.status!%3D499%0AhttpRequest.status!%3D200

**Comment by gfr10598** [comment]
https://pantheon.corp.google.com/logs/viewer?project=mlab-staging&organizationId=433637338589&minLogLevel=0&expandAll=false&timestamp=2018-12-13T22:09:30.339000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2018-12-13T20:40:00.000Z&dateRangeEnd=2018-12-13T22:10:13.000Z&interval=CUSTOM&resource=gae_app%2Fmodule_id%2Fannotator%2Fversion_id%2F20181213t203529&logName=projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&scrollTimestamp=2018-12-13T22:06:17.000000000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22annotator%22%0Aresource.labels.version_id%3D%2220181213t203529%22%0AlogName%3D(%22projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fstderr%22%20OR%20%22projects%2Fmlab-staging%2Flogs%2Fappengine.googleapis.com%252Fnginx.request%22)%0AhttpRequest.status!%3D499%0AhttpRequest.status!%3D502

**Comment by yachang** [comment]
reproduced this crash on sandbox: when the loaded datasets reach limits, and tried to remove some dataset and load the new ones, the removed one still took requests, and caused instance crash.

**Comment by gfr10598** [comment]
log.Fatal looks plausible.  A number of these were observed during the Bad Gateway period:
https://pantheon.corp.google.com/logs/viewer?project=mlab-sandbox&organizationId=433637338589&resource=gae_app%2Fmodule_id%2Fannotator%2Fversion_id%2F20190103t183939&minLogLevel=0&expandAll=false&timestamp=2019-01-03T20:18:39.646000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-01-03T20:11:00.708Z&dateRangeEnd=2019-01-03T20:20:00.708Z&interval=CUSTOM&logName=projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fstderr&logName=projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fnginx.request&scrollTimestamp=2019-01-03T20:15:58.000000000Z&advancedFilter=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22annotator%22%0Aresource.labels.version_id%3D%2220190103t183939%22%0AlogName%3D(%22projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fstderr%22%20OR%20%22projects%2Fmlab-sandbox%2Flogs%2Fappengine.googleapis.com%252Fnginx.request%22)%0AhttpRequest.status!%3D200%0AhttpRequest.status!%3D500%0AhttpRequest.status!%3D503%0A-%22geo-g2.go:239%22%0AhttpRequest.status!%3D502%0A%22loader.go%22

**Comment by gfr10598** [comment]
Looking at a single instance - ("main.go" OR "loader.go")

2019-01-03 20:11:26.000 GMT
2019/01/03 20:11:26 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:27.000 GMT
2019/01/03 20:11:27 main.go:54: Beginning Setup
2019-01-03 20:11:29.000 GMT
2019/01/03 20:11:29 main.go:66: Listening on port 8080
2019-01-03 20:11:30.000 GMT
2019/01/03 20:11:30 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:31.000 GMT
2019/01/03 20:11:31 main.go:54: Beginning Setup
2019-01-03 20:11:34.000 GMT
2019/01/03 20:11:34 main.go:66: Listening on port 8080
2019-01-03 20:11:38.000 GMT
2019/01/03 20:11:38 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:39.000 GMT
2019/01/03 20:11:39 main.go:54: Beginning Setup
2019-01-03 20:11:41.000 GMT
2019/01/03 20:11:41 main.go:66: Listening on port 8080
2019-01-03 20:11:42.000 GMT
2019/01/03 20:11:42 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:43.000 GMT
2019/01/03 20:11:43 main.go:54: Beginning Setup
2019-01-03 20:11:45.000 GMT
2019/01/03 20:11:45 main.go:66: Listening on port 8080
2019-01-03 20:11:47.000 GMT
2019/01/03 20:11:47 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:49.000 GMT
2019/01/03 20:11:49 main.go:54: Beginning Setup
2019-01-03 20:11:51.000 GMT
2019/01/03 20:11:51 main.go:66: Listening on port 8080
2019-01-03 20:11:54.000 GMT
2019/01/03 20:11:54 loader.go:84: storage: object doesn't exist
2019-01-03 20:11:58.000 GMT
2019/01/03 20:11:58 main.go:54: Beginning Setup
2019-01-03 20:12:00.000 GMT
2019/01/03 20:12:00 main.go:66: Listening on port 8080
2019-01-03 20:12:01.000 GMT
2019/01/03 20:12:01 loader.go:84: storage: object doesn't exist
2019-01-03 20:12:08.000 GMT
2019/01/03 20:12:08 main.go:54: Beginning Setup
2019-01-03 20:12:10.000 GMT
2019/01/03 20:12:10 main.go:66: Listening on port 8080
2019-01-03 20:12:15.000 GMT
2019/01/03 20:12:15 loader.go:84: storage: object doesn't exist
2019-01-03 20:12:28.000 GMT
2019/01/03 20:12:28 main.go:54: Beginning Setup
2019-01-03 20:12:30.000 GMT
2019/01/03 20:12:30 main.go:66: Listening on port 8080
2019-01-03 20:12:35.000 GMT
2019/01/03 20:12:35 loader.go:84: storage: object doesn't exist
2019-01-03 20:13:01.000 GMT
2019/01/03 20:13:01 main.go:54: Beginning Setup
2019-01-03 20:13:03.000 GMT
2019/01/03 20:13:03 main.go:66: Listening on port 8080
2019-01-03 20:13:08.000 GMT
2019/01/03 20:13:08 loader.go:84: storage: object doesn't exist
2019-01-03 20:14:00.000 GMT
2019/01/03 20:14:00 main.go:54: Beginning Setup
2019-01-03 20:14:02.000 GMT
2019/01/03 20:14:02 main.go:66: Listening on port 8080
2019-01-03 20:14:06.000 GMT
2019/01/03 20:14:06 loader.go:84: storage: object doesn't exist
2019-01-03 20:15:49.000 GMT
2019/01/03 20:15:49 main.go:54: Beginning Setup
2019-01-03 20:15:52.000 GMT
2019/01/03 20:15:52 main.go:66: Listening on port 8080
2019-01-03 20:15:58.000 GMT
2019/01/03 20:15:58 loader.go:84: storage: object doesn't exist

**Comment by pboothe** [comment]
Fixed.
