### ISSUE TITLE
legacy unittest failed on local machine but pass on travis

### ISSUE THREAD

**Issue by yachang** [m-lab/annotation-service#164]
2019/01/03 11:50:37 &{0x20259c0 0x2024040 0x7f82b17e7010 <nil> 0x2024940 2 [0 0 0 0 0 0 0] 1543870511 1 [0 0 0 0] 20539238 3 [0 0 0] 1 0 0 0 0 1 [0 0 0 0]}
--- FAIL: TestOpenAndFree (0.01s)
    geoip_test.go:24: Not correctly freed

For unknown reason, the file pointer was not set to nil after space freed on local machine

**Comment by gfr10598** [comment]
Also see #123

**Comment by yachang** [comment]
Fixed by #176
