### ISSUE TITLE
Seeing lots of "loading" responses

### ISSUE THREAD

**Issue by gfr10598** [m-lab/annotation-service#178]
For v2 api on sandbox-semaphores-rebase branch, seeing (in the metrics) lots of "v2 reject (loading) 400+".  But there don't seem to be lots of annotators loading, so there must be an inconsistency in the code somewhere.

**Comment by gfr10598** [comment]
Shutting down 20190111t194518 (which is at master?) to avoid pollution of metrics dashboards.

**Comment by gfr10598** [comment]
Found that dataset "total" vs metric disagreement.
Found log entries:
A  2019/01/12 19:21:16 manager.go:237: Loading error Fail to load IPv4 dataset 
A  2019/01/12 03:10:51 manager.go:237: Loading error Fail to load IPv6 dataset 
A  2019/01/12 19:21:16 manager.go:237: Loading error Fail to load IPv4 dataset

This lead to locating logic error when there is an error loading a dataset.  Fixed the bug with temporary hack that allows retry.  Probably should have more sophisticated logic to allow persistent error, and retry loading at a later time.

**Comment by gfr10598** [comment]
This bug causes v2 clients to continuously retry until timeout, and never succeed.  This kills the throughput for v2 clients.  Currently, only SS uses the v2 api, which likely explains why SS was misbehaving on Friday.

**Comment by gfr10598** [comment]
commit "fix bug on load error" was deployed around 10:15 pm.  Clearly enabled sidestream to start making progress again.

Probably the safest thing to do for staging and prod is to disable legacy datasets again.  When we have this prototype code reviewed and checked in, we can re-enable legacy in prod.

**Comment by gfr10598** [comment]
I've created "no-legacy" which actually just avoids datasets prior to 2014/02/07.  This is likely adequate to run in prod in the short term.

Prod is currently broken - annotation rate is extremely slow.  Should probably deploy this soon, at least as an experiment.

**Comment by gfr10598** [comment]
Unpaired datasets:
gs://downloader-mlab-oti/Maxmind/2013/09/07/20130907T170000Z-GeoLiteCity.dat.gz
gs://downloader-mlab-oti/Maxmind/2014/01/07/20140107T160000Z-GeoLiteCityv6.dat.gz
gs://downloader-mlab-oti/Maxmind/2017/10/04/20171004T191815Z-GeoLiteCity.dat.gz
gs://downloader-mlab-oti/Maxmind/2018/04/04/20180404T030048Z-GeoLiteCityv6.dat.gz

**Comment by gfr10598** [comment]
FYI, there are MANY unpaired IPASN datasets.

**Comment by pboothe** [comment]
Obsolete.
