### ISSUE TITLE
High BadIP rate seems to be from sidestream geolite2 annotations.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/annotation-service#256]
This grafana dashboard shows close correlation between sidestream geolite2 request rate (lower left panel) and Bad IP rate, (second row, right panel).

https://grafana.mlab-sandbox.measurementlab.net/d/uJ-abYEiz/pipeline-annotation-service-gfr?orgId=1&from=1559456350387&to=1559466834881&var-interval=10m&var-service=All&var-datasource=Prometheus%20(mlab-staging)&var-request_source=All

**Comment by mehtab11** [comment]
Part of DevTracker # 253

**Comment by pboothe** [comment]
Likely part of m-lab/dev-tracker#253
