### ISSUE TITLE
Reuse LoadASNDatasetFromReader instead of loadData

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/annotation-service#271]
https://github.com/m-lab/annotation-service/pull/270 added asn.LoadASNDatasetFromReader to export that functionality for the uuid-annotator and because existing functions wrote intermediate files to disk.

The current implementation of `loadData` should be eliminated in favor or reusing asn.LoadASNDatasetFromReader in its place in `asn.LoadASNDataset`

**Comment by mehtab11** [comment]
Done.
